apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\temp\forks\example-voting-app\kompose\kompose.exe convert
    kompose.version: 1.8.0 (0c0c027)
  creationTimestamp: null
  labels:
    io.kompose.service: redis
  name: redis
spec:
  ports:
  - name: "6379"
    port: 6379
    targetPort: 6379
  selector:
    io.kompose.service: redis
status:
  loadBalancer: {}
