apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\temp\forks\example-voting-app\kompose\kompose.exe convert
    kompose.version: 1.8.0 (0c0c027)
  creationTimestamp: null
  labels:
    io.kompose.service: worker
  name: worker
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    io.kompose.service: worker
status:
  loadBalancer: {}
